# Writes a synthetic session and censuses it. Fails on any unknown type,
# length mismatch, or missing end-of-session marker.
set(SESSION "${CMAKE_CURRENT_BINARY_DIR}/roundtrip.itch")
execute_process(COMMAND ${GEN} ${SESSION} 200000 7 RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "gen_synthetic failed")
endif()
execute_process(COMMAND ${CENSUS} ${SESSION} OUTPUT_VARIABLE out RESULT_VARIABLE rc)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "census failed")
endif()
if(NOT out MATCHES "unknown type      0")
  message(FATAL_ERROR "unknown message types in a stream we wrote ourselves")
endif()
if(NOT out MATCHES "length mismatch   0")
  message(FATAL_ERROR "length mismatch in a stream we wrote ourselves")
endif()
if(NOT out MATCHES "end-of-session    yes")
  message(FATAL_ERROR "no end-of-session marker")
endif()
message(STATUS "roundtrip ok")
